- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Enable and start uwsgi-lemur
  ansible.builtin.service:
    name: uwsgi-lemur
    enabled: true
    state: restarted
